import { STREAM_STATUS } from './stream.js';

export const EVENT_TYPES = {
  NEW_BOOKMARK: 'NEW_BOOKMARK',
  TITLE_CHANGED: 'TITLE_CHANGED',
  THUMBNAIL_CHANGED: 'THUMBNAIL_CHANGED',
  TYPE_DETECTED: 'TYPE_DETECTED',
  YOUTUBE_NEW_VIDEO: 'YOUTUBE_NEW_VIDEO',
  LIVE_STARTED: 'LIVE_STARTED',
  LIVE_ENDED: 'LIVE_ENDED',
  TWITCH_LIVE_STARTED: 'LIVE_STARTED',
  TWITCH_LIVE_ENDED: 'LIVE_ENDED',
  SITE_DOWN: 'SITE_DOWN',
  SITE_UP: 'SITE_UP',
};

/** Estados de bookmark visibles en la sección Novedades del dashboard */
export const NEWS_BOOKMARK_STATUSES = [
  STREAM_STATUS.LIVE,
];

export { ACTIVITY_EVENT_TYPES } from './activity-events.js';