export const PROCESSOR_NAMES = {
  LIVE: 'live',
  TAG: 'tag',
  FOLDER: 'folder',
};

export const DEFAULT_PROCESSOR_ORDER = [
  PROCESSOR_NAMES.LIVE,
  PROCESSOR_NAMES.TAG,
  PROCESSOR_NAMES.FOLDER,
];

export const DEFAULT_ENABLED_PROCESSORS = [...DEFAULT_PROCESSOR_ORDER];

export const KNOWN_PROCESSORS = new Set(DEFAULT_PROCESSOR_ORDER);
